[package]
name = "dutlink-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.11.0"
prost = "0.12.6"
rusb = "0.9.4"

[build-dependencies]
tonic-build = "0.11.0"
