apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dutlinks.jumpstarter.example.com
spec:
  group: jumpstarter.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
  scope: Namespaced
  names:
    plural: dutlinks
    singular: dutlink
    kind: DutLink
    shortNames:
    - dl
